version: '3.8'
services:
  server:
    build: ./server
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app/server
    environment:
      - MONGO_URI=mongodb://tech-news-mongo:27017/test
      - JWT_SECRET="s3creTt0k3n"
      - PORT=5000
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app/client

  db:
    image: mongo
    container_name: tech-news-mongo
    ports:
      - '27017:27017'
