version: '3.8'
services:
  web:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - .:/app/server
    environment:
      - MONGO_URI=mongodb://tech-news-mongo:27017/test
      - JWT_SECRET="s3creTt0k3n"
      - PORT=5000

  db:
    image: mongo
    container_name: tech-news-mongo
    ports:
      - '27017:27017'
